spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/jeorigagye?autoReconnect=true
    username: jpa
    password: jpa1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#\        show_sql: true # sysout을 통한 디버그

logging:
  level:
    org.hibernate.SQL: debug # Logger를 통한 디버그
    org.hibernate.type: trace # Query parameter 확인 => P6Spy lib 이용

security:
  jwtKey: bbung
